# Generated by Django 2.2.6 on 2020-11-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201118_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'id', 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
