# Generated by Django 2.2.6 on 2020-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201201_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Кртинка к записи.', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
