# Generated by Django 2.2.6 on 2020-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201201_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите имя тега.', max_length=50, verbose_name='Имя тэга')),
                ('slug', models.SlugField(help_text='Укажите адрес для страницы тега.', unique=True, verbose_name='Ключ для построения ссылки')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('title',),
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user',), 'verbose_name': 'Подписка(у)', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'id', 'ordering': ('title',), 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, help_text='Число просмотров записи.', verbose_name='Число просмотров'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Сообщество, с которым связана запись.', null=True, related_name='posts', to='posts.Tag', verbose_name='Сообщество'),
        ),
    ]
