# Generated by Django 2.2.6 on 2020-12-02 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20201202_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text='Связь поста пользователями через отношение лайка.', related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги, подходящие к записи.', null=True, related_name='posts', to='posts.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Введите имя тега.', max_length=50, verbose_name='Имя тега'),
        ),
    ]
