# Generated by Django 2.2.6 on 2020-12-03 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20201202_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text='Связь поста c пользователями через отношение лайка.', related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
    ]
