# Generated by Django 2.2.6 on 2020-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0022_auto_20201203_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги, подходящие к записи.', related_name='posts',
                                         to='posts.Tag', verbose_name='Теги'),
        ),
    ]
