# Generated by Django 2.2.6 on 2020-12-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20201205_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
