# Generated by Django 2.2.6 on 2020-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
