# Generated by Django 2.2.6 on 2020-12-15 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0028_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(help_text=('Связь комментария c пользователями ', 'через отношение дизлайка.'), related_name='dislike_comments', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(help_text=('Связь поста c пользователями ', 'через отношение дизлайка.'), related_name='dislike_posts', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(help_text=('Связь комментария c пользователями', ' через отношение лайка.'), related_name='like_comments', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text=('Связь поста c пользователями ', 'через отношение лайка.'), related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
    ]
