# Generated by Django 2.2.6 on 2020-12-18 07:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20201215_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(help_text=('Связь поста c пользователями ', 'через отношение дизлайка.'), related_name='dislikes_post', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text=('Связь поста c пользователями ', 'через отношение лайка.'), related_name='likes_post', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Введите текст новой записи.', verbose_name='Текст'),
        ),
    ]
